// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameComment = "comment"

// Comment mapped from table <comment>
type Comment struct {
	Cid       int64     `gorm:"column:cid;primaryKey;autoIncrement:true" json:"cid"`           // 主键
	Vid       int64     `gorm:"column:vid;not null" json:"vid"`                                // 视频id
	UID       int64     `gorm:"column:uid;not null" json:"uid"`                                // 用户id
	Content   string    `gorm:"column:content;not null" json:"content"`                        // 评论内容，不能超过255字符
	CreatedAt time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"` // 创建时间
	UpdatedAt time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"` // 更新时间
}

// TableName Comment's table name
func (*Comment) TableName() string {
	return TableNameComment
}
