// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUserAuth = "user_auth"

// UserAuth mapped from table <user_auth>
type UserAuth struct {
	UID             int64     `gorm:"column:uid;primaryKey;autoIncrement:true" json:"uid"`           // 主键
	UserName        string    `gorm:"column:user_name;not null" json:"user_name"`                    // 用户名
	Password        string    `gorm:"column:password;not null" json:"password"`                      // 密码
	FollowCount     int64     `gorm:"column:follow_count" json:"follow_count"`                       // 关注人数
	FollowerCount   string    `gorm:"column:follower_count;default:0" json:"follower_count"`         // 粉丝总数
	IsFollow        bool      `gorm:"column:is_follow" json:"is_follow"`                             // 是否关注，true-已关注，false-未关注
	Avatar          string    `gorm:"column:avatar" json:"avatar"`                                   // 用户头像
	BackgroundImage string    `gorm:"column:background_image" json:"background_image"`               // 用户个人页顶部大图
	Signature       string    `gorm:"column:signature" json:"signature"`                             // 个人简介
	TotalFavorite   string    `gorm:"column:total_favorite" json:"total_favorite"`                   // 获赞数量
	WorkCount       int64     `gorm:"column:work_count" json:"work_count"`                           // 作品数
	FavoriteCount   int64     `gorm:"column:favorite_count" json:"favorite_count"`                   // 喜欢数
	Status          bool      `gorm:"column:status;default:1" json:"status"`                         // 是否删除 1:是  0:否
	CreatedAt       time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"` // 创建时间
	UpdatedAt       time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"` // 更新时间
}

// TableName UserAuth's table name
func (*UserAuth) TableName() string {
	return TableNameUserAuth
}
