// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameFollowUser = "follow_user"

// FollowUser mapped from table <follow_user>
type FollowUser struct {
	ID        int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`             // 主键
	UserID    string    `gorm:"column:user_id" json:"user_id"`                                 // 用户id
	FollowID  string    `gorm:"column:follow_id" json:"follow_id"`                             // 关注id
	Status    bool      `gorm:"column:status;default:1" json:"status"`                         // 是否删除 1:是  0:否
	CreatedAt time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"` // 创建时间
	UpdatedAt time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"` // 更新时间
}

// TableName FollowUser's table name
func (*FollowUser) TableName() string {
	return TableNameFollowUser
}
