// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUserAuth = "user_auth"

// UserAuth mapped from table <user_auth>
type UserAuth struct {
	UID       int64     `gorm:"column:uid;primaryKey;autoIncrement:true" json:"uid"`           // 主键
	UserName  string    `gorm:"column:user_name;not null" json:"user_name"`                    // 用户名
	Password  string    `gorm:"column:password;not null" json:"password"`                      // 密码
	Status    bool      `gorm:"column:status;default:1" json:"status"`                         // 是否删除 1:是  0:否
	CreatedAt time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"` // 创建时间
	UpdatedAt time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"` // 更新时间
}

// TableName UserAuth's table name
func (*UserAuth) TableName() string {
	return TableNameUserAuth
}
