// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameVideo = "video"

// Video mapped from table <video>
type Video struct {
	Vid       int64     `gorm:"column:vid;primaryKey;autoIncrement:true" json:"vid"`           // 主键
	UID       int64     `gorm:"column:uid;not null" json:"uid"`                                // 作者
	PlayURL   string    `gorm:"column:play_url;not null" json:"play_url"`                      // 播放地址
	CoverURL  string    `gorm:"column:cover_url;not null" json:"cover_url"`                    // 封面地址
	Status    bool      `gorm:"column:status;default:1" json:"status"`                         // 是否删除 1:是  0:否
	CreatedAt time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"` // 创建时间
	UpdatedAt time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"` // 更新时间
}

// TableName Video's table name
func (*Video) TableName() string {
	return TableNameVideo
}
