// Code generated by hertz generator.

package user

import (
	"context"
	"net/http"
	"strconv"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	user "github.com/simplecolding/douyin/hertz-server/biz/model/hertz/user"
	"github.com/simplecolding/douyin/hertz-server/biz/mw"
	_ "github.com/simplecolding/douyin/hertz-server/biz/mw"
	_ "github.com/simplecolding/douyin/hertz-server/biz/orm" //
	"github.com/simplecolding/douyin/hertz-server/biz/orm/dal"
	"github.com/simplecolding/douyin/hertz-server/biz/orm/model"
)

// UserLogin .
// @router /douyin/user/login [POST]
func UserLogin(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.DouyinUserRegisterRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	mw.Init()
	mw.JwtMiddleware.LoginHandler(ctx, c)

	//mw.JwtMiddleware.ParseTokenString()
	//redisCtx, cancel := context.WithTimeout(context.Background(), 500*time.Millisecond)
	//defer cancel()
	//resp := new(user.DouyinUserLoginResponse)
	//tk := "hisadfgh"
	//resp.Token = tk
	////redis.RD.Set(ctx, req.Username, tk, 10*time.Minute)
	////println(redis.RD.Get(ctx, req.Username).Val())
	//c.JSON(consts.StatusOK, resp)

	// mc := mw.JwtMiddleware.Key
	// respCookie := protocol.AcquireCookie()
	// respCookie.SetKey(string(mc))
	// c.Response.Header.Cookie(respCookie)
	// token := respCookie.token
	// fmt.Println("token: ", tokenString)
	// println("cookie: ", respCookie)
	/*
		loginResp := mw.JwtMiddleware.LoginResponse

		//获取token
		tmp := json.loads(loginResp)
		token := tmp["token"]
		println("token: ", token)
	*/

	// resp.UserId = u.UID
	// resp.StatusCode = int32(0)
	// resp.StatusMsg = "success"
	// resp.Token = tokenString
	//println(mw.JwtMiddleware.GetClaimsFromJWT(ctx, c))
	//redisCtx, cancel := context.WithTimeout(context.Background(), 500*time.Millisecond)
	//defer cancel()
	//resp := new(user.DouyinUserLoginResponse)
	//tk := "hisadfgh"
	//resp.Token = tk
	//redis.RD.Set(ctx, req.Username, tk, 10*time.Minute)
	//println(redis.RD.Get(ctx, req.Username).Val())
	// c.JSON(consts.StatusOK, resp)
}

// UserRegister .
// @router /douyin/user/register [POST]
func UserRegister(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.DouyinUserRegisterRequest
	resp := new(user.DouyinUserRegisterResponse)
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	username := req.Username
	password := req.Password
	if len(username) < 6 || len(password) < 6 {
		resp.StatusCode = 1
		resp.StatusMsg = "username must gt 6 and password must gt 6!!!"
		c.JSON(consts.StatusOK, resp)
		return
	}
	// query
	u, err := dal.UserAuth.Where(dal.UserAuth.UserName.Eq(username)).First()
	if u != nil {
		resp.UserId = -1
		resp.StatusCode = 1
		resp.StatusMsg = "failed!  username已存在！！！" + username
		c.JSON(consts.StatusOK, resp)
		return
	}
	userinfo := model.UserAuth{UserName: username, Password: password}
	err = dal.UserAuth.Create(&userinfo)
	if err != nil {
		resp.UserId = -1
		resp.StatusCode = 1
		resp.StatusMsg = "failed!  插入失败！！！"
		c.JSON(consts.StatusOK, resp)
		return
	}

	resp.UserId = userinfo.UID
	resp.StatusCode = 0
	resp.StatusMsg = "success"
	c.JSON(0, resp)
}

// UserInfo .
// @router /douyin/user [POST]
func UserInfo(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.DouyinUserRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	// 注意这里
	u, _ := c.Get(mw.IdentityKey)
	println(u.(*mw.Claim).ID, u.(*mw.Claim).Username)
	//tk := req.Token
	//jwtToken, err := mw.JwtMiddleware.ParseTokenString(tk)
	//tmp := jwt.ExtractClaimsFromToken(jwtToken)
	//tmp[mw.IdentityKey]

	dal.UserAuth.Where(dal.UserAuth.UID.Eq(u.(*mw.Claim).ID))
	totalFavorited := int64(0)
	v, err := dal.Video.Where(dal.Video.UID.Eq(u.(*mw.Claim).ID)).Find()
	for _, t := range v {
		tmpcount, _ := dal.Favorite.Where(dal.Favorite.Vid.Eq(t.Vid)).Count()
		totalFavorited += tmpcount
	}
	// 低性能代码
	workCount, _ := dal.Video.Where(dal.Video.UID.Eq(u.(*mw.Claim).ID)).Count()
	favoriteCount, _ := dal.Favorite.Where(dal.Favorite.UID.Eq(u.(*mw.Claim).ID)).Count()
	userInfoDB, err := dal.UserAuth.Where(dal.UserAuth.UID.Eq(u.(*mw.Claim).ID)).First()
	if err != nil {
		println("database err")
	}
	userInfoDB.WorkCount = workCount
	userInfoDB.FavoriteCount = favoriteCount
	userInfoDB.TotalFavorite = strconv.FormatInt(totalFavorited, 10)
	dal.UserAuth.Save(userInfoDB)
	resp := new(user.DouyinUserResponse)
	resp.StatusCode = int32(0)
	resp.StatusMsg = "success"
	resp.User = &user.User{
		Id:              userInfoDB.UID,
		Name:            userInfoDB.UserName,
		FollowCount:     userInfoDB.FollowCount,
		IsFollow:        userInfoDB.IsFollow,
		Avatar:          userInfoDB.Avatar,
		BackgroundImage: userInfoDB.BackgroundImage,
		Signature:       userInfoDB.Signature,
		TotalFavorited:  userInfoDB.TotalFavorite,
		WorkCount:       userInfoDB.WorkCount,
		FavoriteCount:   userInfoDB.FavoriteCount,
	}
	c.JSON(http.StatusOK, resp)
	return
}
